### ISSUE TITLE
No module named 'kubernetes'

### ISSUE THREAD

**Issue by noseka1** [opendatahub-io-contrib/docker-airflow#3]
Trying to create an Airflow cluster using the following resource manifest:

```
apiVersion: airflow.apache.org/v1alpha1
kind: AirflowCluster
metadata:
  name: pk-cluster
spec:
  executor: Kubernetes
  ui:
    replicas: 1
    image: "quay.io/opendatahub/docker-airflow"
    version: "openshift"
  scheduler:
    image: "quay.io/opendatahub/docker-airflow"
    version: "openshift"
  worker:
    image: "quay.io/opendatahub/docker-airflow"
    version: "openshift"
  dags:
    subdir: "airflow/example_dags/"
    git:
      repo: "https://github.com/apache/airflow/"
      once: true
      branch: master
  airflowbase:
    name: pc-base
```

The airflowui and scheduler components fail to start:

```
NAME                                                            READY   STATUS             RESTARTS   AGE
pod/airflow-on-k8s-operator-controller-manager-69f6459f-j24tq   1/1     Running            0          3h13m
pod/pc-base-postgres-0                                          1/1     Running            0          82m
pod/pk-cluster-airflowui-0                                      0/1     Error              9          25m
pod/pk-cluster-scheduler-0                                      1/2     CrashLoopBackOff   9          25m
```

They fail because the Python kubernetes library is not included in the container image:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 1013, in scheduler
    do_pickle=args.do_pickle)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 380, in __init__
    super(SchedulerJob, self).__init__(*args, **kwargs)
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 86, in __init__
    self.executor = executor or executors.get_default_executor()
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/__init__.py", line 48, in get_default_executor
    DEFAULT_EXECUTOR = _get_executor(executor_name)
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/__init__.py", line 86, in _get_executor
    from airflow.contrib.executors.kubernetes_executor import KubernetesExecutor
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 30, in <module>
    import kubernetes
ModuleNotFoundError: No module named 'kubernetes'
```

**Comment by vpavlin** [comment]
Fixed by #4
